#====================================================================================================================================#
#                                                                                                                                    #
#     :::       :::  ::::::::  :::::::::  :::        :::::::::   ::::::::  :::::::::: :::::::::  :::     ::: :::::::::: :::::::::    #
#     :+:       :+: :+:    :+: :+:    :+: :+:        :+:    :+: :+:    :+: :+:        :+:    :+: :+:     :+: :+:        :+:    :+:   #
#    +:+       +:+ +:+    +:+ +:+    +:+ +:+        +:+    +:+ +:+        +:+        +:+    +:+ +:+     +:+ +:+        +:+    +:+    #
#   +#+  +:+  +#+ +#+    +:+ +#++:++#:  +#+        +#+    +:+ +#++:++#++ +#++:++#   +#++:++#:  +#+     +:+ +#++:++#   +#++:++#:      #
#  +#+ +#+#+ +#+ +#+    +#+ +#+    +#+ +#+        +#+    +#+        +#+ +#+        +#+    +#+  +#+   +#+  +#+        +#+    +#+      #
#  #+#+# #+#+#  #+#    #+# #+#    #+# #+#        #+#    #+# #+#    #+# #+#        #+#    #+#   #+#+#+#   #+#        #+#    #+#       #
#  ###   ###    ########  ###    ### ########## #########   ########  ########## ###    ###     ###     ########## ###    ###        #
#                                                                                                                                    #
#====================================================================================================================================#

#====================================================================================================================================#
#                                                                                                                                    #
#                                               (c) Efnilite 2021. Do not distribute!                                                #
#                                                                                                                                    #
#====================================================================================================================================#

# -= Auto updater =-
# The auto updater will automatically download updates if they are available.
# It's highly recommended to keep this on!
auto-updater: true

# -= Enable per world tab list =-
# True: players not in the same world will be hidden
# False: every player will be visible
tab-enabled: true

# -= Enable per world chat =-
# True: players not in the same world can't chat with each other
# False: chat will be global
chat-enabled: true

# -= Enable global chat =-
# True: players will be able to talk in global chat using a prefix
# False: players are bound to talk in their own world (if enabled)
global-chat-enabled: true

# -= Global chat prefix =-
# The prefix for global chat.
# This is used to be able to type in global chat.
# If you set this to '!', typing '!hello' will be seen by all players.
# This is not a command. Add the prefix (by default '!') in front of your message to access global chat!
global-chat-prefix: '!'

# -= Global chat format =-
# The text format when a message is sent in global chat
# %player% is used to get the player and %message% is to get the message.
global-chat-format: '<#468094>[Global] <white>%player%: %message%'

# -= Spy Format =-
# The message format for when spy mode is enabled for an admin.
# Change this by using /ws menu.
spy-format: '<#abcdef>(%world%) <gray>%player%: %message%'

# -= World groups =-
# Group together worlds to share the tab list and chat
# Have any questions? Join my Discord (https://discord.gg/wRpSWHx)
groups:
    example:
        - 'World-1'
        - 'World-2'
        - 'Nether'

# -= World chat format =-
# Change the chat format for a group of worlds or a specific world
# If conflict happens, groups are prioritized over worlds.
# Have any questions? Join my Discord (https://discord.gg/wRpSWHx)
chat-format:
    example: '<red>[Example World Group] <white>%player%: <gray>%message%' # Example with a group
    MyWorld: '<red>[MyWorld] <gray>%player% - %message%' # Example with a world

# -= Enable per world economy =-
# True: players will have a different balance, depending on which World or World Group they are in.
# False: players will share
economy-enabled: true

# -= Economy switch notification =-
# True: players will receive a message when they switch worlds (or join) detailing how much balance they have
# False: players won't get a message
economy-switch-notification: true

# -= Economy balance notification format =-
# Set the format of the message players get if they switch worlds.
# This will only be set if economy and economy switch notifications are enabled.
economy-switch-format: '<gray>You now have <#1FB4DE>%amount% eurodollars<gray>.'

# -= Economy currency symbol =-
# The economy currency symbol.
economy-currency-symbol: '€$'

# -= Economy currency names =-
# The names of the currency.
# The first entry is for singular, the second for plural.
economy-currency-names:
  - 'eurodollar'
  - 'eurodollars'

# -= Economy starting amount =-
# The amount of money the player will start with in a specific world group if they haven't ever joined that group.
economy-starting-amount:
  example: 1000
  MyWorld: 69.69