#====================================================================================================================================#
#                                                                                                                                    #
#     :::       :::  ::::::::  :::::::::  :::        :::::::::   ::::::::  :::::::::: :::::::::  :::     ::: :::::::::: :::::::::    #
#     :+:       :+: :+:    :+: :+:    :+: :+:        :+:    :+: :+:    :+: :+:        :+:    :+: :+:     :+: :+:        :+:    :+:   #
#    +:+       +:+ +:+    +:+ +:+    +:+ +:+        +:+    +:+ +:+        +:+        +:+    +:+ +:+     +:+ +:+        +:+    +:+    #
#   +#+  +:+  +#+ +#+    +:+ +#++:++#:  +#+        +#+    +:+ +#++:++#++ +#++:++#   +#++:++#:  +#+     +:+ +#++:++#   +#++:++#:      #
#  +#+ +#+#+ +#+ +#+    +#+ +#+    +#+ +#+        +#+    +#+        +#+ +#+        +#+    +#+  +#+   +#+  +#+        +#+    +#+      #
#  #+#+# #+#+#  #+#    #+# #+#    #+# #+#        #+#    #+# #+#    #+# #+#        #+#    #+#   #+#+#+#   #+#        #+#    #+#       #
#  ###   ###    ########  ###    ### ########## #########   ########  ########## ###    ###     ###     ########## ###    ###        #
#                                                                                                                                    #
#====================================================================================================================================#

#====================================================================================================================================#
#                                                                                                                                    #
#                                               (c) Efnilite 2021. Do not distribute!                                                #
#                                                                                                                                    #
#====================================================================================================================================#

# -= Enable global chat =-
# True: players will be able to talk in global chat using a prefix
# False: players are bound to talk in their own world (if enabled)
global-chat-enabled: true

# -= Global chat prefix =-
# The prefix for global chat
# This is used to be able to type in global chat.
# If you set this to '!', typing '!hello' will be seen by all players.
global-chat-prefix: '!'

# -= Global chat format =-
# The text format when a message is sent in global chat
# %player% is used to get the player and %message% is to get the message.
global-chat-format: '<#468094>[Global] <white>%player%: %message%'

# -= Spy Format =-
# The format for when spy mode is enabled.
spy-format: '<#abcdef>(%world%) <gray>%player%: %message%'

# -= World groups =-
# Group together worlds to share the tab list and chat
# Have any questions? Join my Discord (https://discord.gg/wRpSWHx)
groups:
    example:
        - 'World-1'
        - 'World-2'
        - 'Nether'

# -= World chat format =-
# Change the chat format for a group of worlds or a specific world
# If conflict happens, groups are prioritized over worlds.
# Have any questions? Join my Discord (https://discord.gg/wRpSWHx)
chat-format:
    example: '<red>[Example World Group] <white>%player%: <gray>%message%' # Example with a group
    MyWorld: '<red>[MyWorld] <gray>%player% - %message%' # Example with a world

# -= Enable per world chat =-
# True: players not in the same world can't chat with each other
# False: chat will be global
chat-enabled: true

# -= Enable per world tab list =-
# True: players not in the same world will be hidden
# False: every player will be visible
tab-enabled: true