# -= WorldServer =-
# by Efnilite (https://efnilite.dev)
# (c) 2024

# Need help?
# Join my Discord (https://efnilite.dev/discord) or email me (https://efnilite.dev/#contact).

# -= Debug =-
debug: false

# -= Permissions =-
# If true, commands will require permissions.
permissions: false

# -= Locale =-
# The default locale to use if the player's locale is not found.
locale: "en_us"

# -= Shared =-
# Worlds in these groups share chat, tab list, or economy.
# Specify per world which features are shared.
# Examples:
# - 'chat||tab||world_name' will share chat and tab list with the rest of the group in the world 'world_name'.
# - In the lobby section below, chat is shared between world, world_nether and world_the_end, but tab
#   is only shared between world_nether and world_the_end.
shared:
  lobby:
    - 'chat||world'
    - 'chat||tab||world_nether'
    - 'chat||tab||world_the_end'
  factions:
    - 'chat||tab||eco||factions'
    - 'chat||tab||eco||factions_nether'
    - 'chat||tab||eco||factions_the_end'

# -= Tab =-
# If true, hides players not in the player's current world.
tab: true

# -= Chat =-
# If true, chat will be separated per world.
chat: true

# -= Global chat =-
# If true, players can chat globally if they prefix their message with a certain string.
# View the global chat prefix setting to change this.
global-chat: true

# -= Global chat prefix =-
# The prefix for global chat.
# This is used to be able to type in global chat.
# If you set this to '!', typing '!hello' will be seen by all players.
global-chat-prefix: '!'

# -= Clear chat on switch =-
# If true, will clear the chat on a switch of the world.
clear-chat-on-switch: false

# -= Enable per world economy =-
# True: players will have a different balance, depending on which World or World Group they are in.
# False: players will share
eco:

  # -= Economy enabled =-
  enabled: false

  # -= Economy global =-
  # True: the economy will be shared across the entire server
  # False: if economy is enabled, each world or world group will have a different economy.
  global-enabled: false

  # -= Economy switch notification =-
  # True: players will receive a message when they switch worlds (or join) detailing how much balance they have
  # False: players won't get a message
  switch-notification: true

  # -= Economy allow negative balance =-
  # When true, WorldServer will not check if the player has enough balance when withdrawing.
  # This will allow players to have a negative balance.
  allow-negative-balance: false

  # -= Economy starting amount =-
  # The amount of money the player will start with in a specific world group if they haven't ever joined that group.
  starting-amount:
    example: 1000
    MyWorld: 69.69

  # -= Economy balance change =-
  # Sends a message to the player when their balance changes.
  balance-change: true

  currency-symbol: 'E$'
  currency-names:
    singular: 'eurodollar'
    plural: 'eurodollars'