name: WorldServer
version: 2.0.0
api-version: 1.16
website: https://github.com/Efnilite/WorldServer
author: Efnilite
main: dev.efnilite.ws.WS
description: Separate chat, the tab list and the economy in each world.
loadbefore: [Essentials, EssentialsX]
softdepend: [Vault, PlaceholderAPI]
commands:
  ws:
    aliases: [worldserver]
    description: The main command of WorldServer.
  globalchat:
    aliases: [gc, global-chat, global]
    description: Toggle global chat.
  balance:
    aliases: [bal]
    description: Check your balance.
  balancetop:
    aliases: [baltop]
    description: Check the top balances.
  pay:
    description: Pay a player.