name: WorldServer
author: Efnilite
main: dev.efnilite.worldserver.WorldServer
version: 1.5.4
api-version: 1.16
description: Separate chat and tab list in the worlds in your server.
depend: [vilib]
softdepend: [Vault, PlaceholderAPI]
commands:
  worldserver:
    aliases: [ws]
    description: The main command of WorldServer