name: 'WorldServer'
author: 'Efnilite'
main: 'dev.efnilite.worldserver.WorldServer'
version: '1.2.3'
api-version: '1.16'
description: 'Separate chat and tab list in the worlds in your server.'
commands:
    worldserver:
        aliases: [ws]
        description: The main command of WorldServer